# Generated by Django 5.2.5 on 2025-08-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='solved_words',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='total_words',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='tries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='difficulty',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='emoji_input',
            field=models.CharField(max_length=100),
        ),
    ]
