# Generated by Django 5.2.5 on 2025-08-23 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_gamesession_timestamp_gamesession_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_started', models.BooleanField(default=False)),
                ('game_start_time', models.DateTimeField(blank=True, null=True)),
                ('game_end_time', models.DateTimeField(blank=True, null=True)),
                ('total_time_taken', models.DurationField(blank=True, null=True)),
                ('easy_completed', models.BooleanField(default=False)),
                ('medium_completed', models.BooleanField(default=False)),
                ('hard_completed', models.BooleanField(default=False)),
                ('easy_won', models.BooleanField(default=False)),
                ('medium_won', models.BooleanField(default=False)),
                ('hard_won', models.BooleanField(default=False)),
                ('game_completed', models.BooleanField(default=False)),
                ('game_won', models.BooleanField(default=False)),
                ('game_expired', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
